export default [
  {
    id: 'QIW9s',
    name: 'tele joyi',
    selectedUnity: { name: 'Lt', value: 0 },
    perishable: { label: 'Yes', value: true },
    quantity: "1",
    manufacturing: '2021-06-11',
    price: "20.5",
    expiration: '2021-10-22',
  },
  {
    id: '6bLhc',
    name: 'jacksa doyil',
    selectedUnity: { name: 'Lt', value: 0 },
    perishable: { label: 'No', value: false },
    quantity: "1",
    manufacturing: '2021-06-11',
    price: "50.1",
    expiration: '2021-10-22',
  },
  {
    id: '7QTCr',
    name: 'tesamy jaiol',
    selectedUnity: { name: 'Lt', value: 0 },
    perishable: { label: 'Yes', value: true },
    quantity: "5",
    manufacturing: '2021-06-11',
    price: "30.6",
    expiration: '2021-10-22',
  },
  {
    id: 'JYJuk',
    name: 'tecsa jaloiaw',
    selectedUnity: { name: 'Lt', value: 0 },
    perishable: { label: 'Yes', value: true },
    quantity: "3",
    manufacturing: '2021-01-13',
    price: "30.6",
    expiration: '2021-10-22',
  },
  {
    id: 'G6EE9',
    name: 'havye nitrite',
    selectedUnity: { name: 'Lt', value: 0 },
    perishable: { label: 'Yes', value: true },
    quantity: "3",
    manufacturing: '2021-01-01',
    price: "40.6",
    expiration: '2021-10-29',
  },
];
